/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20023Transactions model module.
 * @module model/InlineResponse20023Transactions
 * @version 0.1.1
 */
export class InlineResponse20023Transactions {
  /**
   * Constructs a new <code>InlineResponse20023Transactions</code>.
   * @alias module:model/InlineResponse20023Transactions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20023Transactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20023Transactions} obj Optional instance to populate.
   * @return {module:model/InlineResponse20023Transactions} The populated <code>InlineResponse20023Transactions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20023Transactions();
      if (data.hasOwnProperty('transactionId'))
        obj.transactionId = ApiClient.convertToType(data['transactionId'], 'Number');
      if (data.hasOwnProperty('walletDebitId'))
        obj.walletDebitId = ApiClient.convertToType(data['walletDebitId'], 'Number');
      if (data.hasOwnProperty('walletCreditId'))
        obj.walletCreditId = ApiClient.convertToType(data['walletCreditId'], 'Number');
      if (data.hasOwnProperty('transactionType'))
        obj.transactionType = ApiClient.convertToType(data['transactionType'], 'String');
      if (data.hasOwnProperty('foreignId'))
        obj.foreignId = ApiClient.convertToType(data['foreignId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('valueDate'))
        obj.valueDate = ApiClient.convertToType(data['valueDate'], 'String');
      if (data.hasOwnProperty('executionDate'))
        obj.executionDate = ApiClient.convertToType(data['executionDate'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('walletDebitBalance'))
        obj.walletDebitBalance = ApiClient.convertToType(data['walletDebitBalance'], 'String');
      if (data.hasOwnProperty('walletCreditBalance'))
        obj.walletCreditBalance = ApiClient.convertToType(data['walletCreditBalance'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('totalRows'))
        obj.totalRows = ApiClient.convertToType(data['totalRows'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} transactionId
 */
InlineResponse20023Transactions.prototype.transactionId = undefined;

/**
 * @member {Number} walletDebitId
 */
InlineResponse20023Transactions.prototype.walletDebitId = undefined;

/**
 * @member {Number} walletCreditId
 */
InlineResponse20023Transactions.prototype.walletCreditId = undefined;

/**
 * @member {String} transactionType
 */
InlineResponse20023Transactions.prototype.transactionType = undefined;

/**
 * @member {Number} foreignId
 */
InlineResponse20023Transactions.prototype.foreignId = undefined;

/**
 * @member {String} name
 */
InlineResponse20023Transactions.prototype.name = undefined;

/**
 * @member {String} description
 */
InlineResponse20023Transactions.prototype.description = undefined;

/**
 * Date YYYY-MM-DD
 * @member {String} valueDate
 */
InlineResponse20023Transactions.prototype.valueDate = undefined;

/**
 * Date YYYY-MM-DD
 * @member {String} executionDate
 */
InlineResponse20023Transactions.prototype.executionDate = undefined;

/**
 * @member {String} amount
 */
InlineResponse20023Transactions.prototype.amount = undefined;

/**
 * @member {String} walletDebitBalance
 */
InlineResponse20023Transactions.prototype.walletDebitBalance = undefined;

/**
 * @member {String} walletCreditBalance
 */
InlineResponse20023Transactions.prototype.walletCreditBalance = undefined;

/**
 * @member {String} currency
 */
InlineResponse20023Transactions.prototype.currency = undefined;

/**
 * Date YYYY-MM-DD HH:MM:SS
 * @member {String} createdDate
 */
InlineResponse20023Transactions.prototype.createdDate = undefined;

/**
 * @member {Number} totalRows
 */
InlineResponse20023Transactions.prototype.totalRows = undefined;

