/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2009 model module.
 * @module model/InlineResponse2009
 * @version 0.1.1
 */
export class InlineResponse2009 {
  /**
   * Constructs a new <code>InlineResponse2009</code>.
   * @alias module:model/InlineResponse2009
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2009</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009} The populated <code>InlineResponse2009</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2009();
      if (data.hasOwnProperty('cardId'))
        obj.cardId = ApiClient.convertToType(data['cardId'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('calculationDate'))
        obj.calculationDate = ApiClient.convertToType(data['calculationDate'], 'Date');
    }
    return obj;
  }
}

/**
 * ID of the card
 * @member {Number} cardId
 */
InlineResponse2009.prototype.cardId = undefined;

/**
 * reserved amount of the card
 * @member {Number} amount
 */
InlineResponse2009.prototype.amount = undefined;

/**
 * last calculation date
 * @member {Date} calculationDate
 */
InlineResponse2009.prototype.calculationDate = undefined;

