/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20026Transfers model module.
 * @module model/InlineResponse20026Transfers
 * @version 0.1.1
 */
export class InlineResponse20026Transfers {
  /**
   * Constructs a new <code>InlineResponse20026Transfers</code>.
   * @alias module:model/InlineResponse20026Transfers
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20026Transfers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20026Transfers} obj Optional instance to populate.
   * @return {module:model/InlineResponse20026Transfers} The populated <code>InlineResponse20026Transfers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20026Transfers();
      if (data.hasOwnProperty('transferrefundId'))
        obj.transferrefundId = ApiClient.convertToType(data['transferrefundId'], 'Number');
      if (data.hasOwnProperty('transferrefundTag'))
        obj.transferrefundTag = ApiClient.convertToType(data['transferrefundTag'], 'String');
      if (data.hasOwnProperty('transferrefundStatus'))
        obj.transferrefundStatus = ApiClient.convertToType(data['transferrefundStatus'], 'String');
      if (data.hasOwnProperty('codeStatus'))
        obj.codeStatus = ApiClient.convertToType(data['codeStatus'], 'Number');
      if (data.hasOwnProperty('informationStatus'))
        obj.informationStatus = ApiClient.convertToType(data['informationStatus'], 'String');
      if (data.hasOwnProperty('walletId'))
        obj.walletId = ApiClient.convertToType(data['walletId'], 'Number');
      if (data.hasOwnProperty('transferId'))
        obj.transferId = ApiClient.convertToType(data['transferId'], 'Number');
      if (data.hasOwnProperty('transferrefundDate'))
        obj.transferrefundDate = ApiClient.convertToType(data['transferrefundDate'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('modifiedDate'))
        obj.modifiedDate = ApiClient.convertToType(data['modifiedDate'], 'String');
      if (data.hasOwnProperty('totalRows'))
        obj.totalRows = ApiClient.convertToType(data['totalRows'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} transferrefundId
 */
InlineResponse20026Transfers.prototype.transferrefundId = undefined;

/**
 * @member {String} transferrefundTag
 */
InlineResponse20026Transfers.prototype.transferrefundTag = undefined;

/**
 * Allowed values for the <code>transferrefundStatus</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse20026Transfers.TransferrefundStatusEnum = {
  /**
   * value: "PENDING"
   * @const
   */
  PENDING: "PENDING",

  /**
   * value: "CANCELED"
   * @const
   */
  CANCELED: "CANCELED",

  /**
   * value: "VALIDATED"
   * @const
   */
  VALIDATED: "VALIDATED"
};
/**
 * @member {module:model/InlineResponse20026Transfers.TransferrefundStatusEnum} transferrefundStatus
 */
InlineResponse20026Transfers.prototype.transferrefundStatus = undefined;

/**
 * @member {Number} codeStatus
 */
InlineResponse20026Transfers.prototype.codeStatus = undefined;

/**
 * @member {String} informationStatus
 */
InlineResponse20026Transfers.prototype.informationStatus = undefined;

/**
 * @member {Number} walletId
 */
InlineResponse20026Transfers.prototype.walletId = undefined;

/**
 * @member {Number} transferId
 */
InlineResponse20026Transfers.prototype.transferId = undefined;

/**
 * @member {Number} transferrefundDate
 */
InlineResponse20026Transfers.prototype.transferrefundDate = undefined;

/**
 * @member {String} amount
 */
InlineResponse20026Transfers.prototype.amount = undefined;

/**
 * @member {String} currency
 */
InlineResponse20026Transfers.prototype.currency = undefined;

/**
 * Date YYYY-MM-DD HH:MM:SS
 * @member {String} createdDate
 */
InlineResponse20026Transfers.prototype.createdDate = undefined;

/**
 * Date YYYY-MM-DD HH:MM:SS
 * @member {String} modifiedDate
 */
InlineResponse20026Transfers.prototype.modifiedDate = undefined;

/**
 * @member {Number} totalRows
 */
InlineResponse20026Transfers.prototype.totalRows = undefined;

