/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse20020PayoutRefunds} from './InlineResponse20020PayoutRefunds';

/**
 * The InlineResponse20020 model module.
 * @module model/InlineResponse20020
 * @version 0.1.1
 */
export class InlineResponse20020 {
  /**
   * Constructs a new <code>InlineResponse20020</code>.
   * @alias module:model/InlineResponse20020
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20020</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20020} obj Optional instance to populate.
   * @return {module:model/InlineResponse20020} The populated <code>InlineResponse20020</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20020();
      if (data.hasOwnProperty('payoutRefunds'))
        obj.payoutRefunds = ApiClient.convertToType(data['payoutRefunds'], [InlineResponse20020PayoutRefunds]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse20020PayoutRefunds>} payoutRefunds
 */
InlineResponse20020.prototype.payoutRefunds = undefined;

