/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BeneficiariesSddB2bWhitelist} from './BeneficiariesSddB2bWhitelist';

/**
 * The InlineResponse2003Beneficiaries model module.
 * @module model/InlineResponse2003Beneficiaries
 * @version 0.1.1
 */
export class InlineResponse2003Beneficiaries {
  /**
   * Constructs a new <code>InlineResponse2003Beneficiaries</code>.
   * @alias module:model/InlineResponse2003Beneficiaries
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2003Beneficiaries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003Beneficiaries} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003Beneficiaries} The populated <code>InlineResponse2003Beneficiaries</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003Beneficiaries();
      if (data.hasOwnProperty('tag'))
        obj.tag = ApiClient.convertToType(data['tag'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('nickName'))
        obj.nickName = ApiClient.convertToType(data['nickName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('iban'))
        obj.iban = ApiClient.convertToType(data['iban'], 'String');
      if (data.hasOwnProperty('bic'))
        obj.bic = ApiClient.convertToType(data['bic'], 'String');
      if (data.hasOwnProperty('sepaCreditorIdentifier'))
        obj.sepaCreditorIdentifier = ApiClient.convertToType(data['sepaCreditorIdentifier'], 'String');
      if (data.hasOwnProperty('sddB2bWhitelist'))
        obj.sddB2bWhitelist = ApiClient.convertToType(data['sddB2bWhitelist'], [BeneficiariesSddB2bWhitelist]);
      if (data.hasOwnProperty('sddCoreBlacklist'))
        obj.sddCoreBlacklist = ApiClient.convertToType(data['sddCoreBlacklist'], ['String']);
      if (data.hasOwnProperty('usableForSct'))
        obj.usableForSct = ApiClient.convertToType(data['usableForSct'], 'Boolean');
      if (data.hasOwnProperty('sddCoreKnownUniqueMandateReference'))
        obj.sddCoreKnownUniqueMandateReference = ApiClient.convertToType(data['sddCoreKnownUniqueMandateReference'], ['String']);
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('modifiedDate'))
        obj.modifiedDate = ApiClient.convertToType(data['modifiedDate'], 'String');
    }
    return obj;
  }
}

/**
 * Custom data that could be used by caller to search the instance.
 * @member {String} tag
 */
InlineResponse2003Beneficiaries.prototype.tag = undefined;

/**
 * Beneficiary's userId
 * @member {Number} userId
 */
InlineResponse2003Beneficiaries.prototype.userId = undefined;

/**
 * Name choosen by end user to easily recognize the beneficiary.
 * @member {String} nickName
 */
InlineResponse2003Beneficiaries.prototype.nickName = undefined;

/**
 * Beneficiary name, linked to bank account.
 * @member {String} name
 */
InlineResponse2003Beneficiaries.prototype.name = undefined;

/**
 * Beneficiary address, linked to bank account.
 * @member {String} address
 */
InlineResponse2003Beneficiaries.prototype.address = undefined;

/**
 * Beneficiary International Bank Account Number.
 * @member {String} iban
 */
InlineResponse2003Beneficiaries.prototype.iban = undefined;

/**
 * Beneficiary Bank Identifier Code.
 * @member {String} bic
 */
InlineResponse2003Beneficiaries.prototype.bic = undefined;

/**
 * Beneficiary SEPA Creditor Identifier. Mandatory to validate B2B incoming direct debit, useless other wise. Between 8 and 35 caracters.
 * @member {String} sepaCreditorIdentifier
 */
InlineResponse2003Beneficiaries.prototype.sepaCreditorIdentifier = undefined;

/**
 * Each unique mandate reference, with its frequency type, must be explicitely allowed when doing B2B Direct Debit. Furthermore, a mandate not used during more than 36 months will be automatically rejected even if in the white list.
 * @member {Array.<module:model/BeneficiariesSddB2bWhitelist>} sddB2bWhitelist
 */
InlineResponse2003Beneficiaries.prototype.sddB2bWhitelist = undefined;

/**
 * Core Direct Debit are accepted by default. If a Core mandate is to be refused on reception, it has to be added to this list. If wild char * (star) is used instead of a UMR, all Direct Debit from this beneficiary will be refused. Note that the mandate ref entered is case sensitive.
 * @member {Array.<String>} sddCoreBlacklist
 */
InlineResponse2003Beneficiaries.prototype.sddCoreBlacklist = undefined;

/**
 * Indicated if the beneficiary can be used for SEPA Credit Transfer. This field is a conveniant way to filter all beneficiaries for a user that would like to do a Credit Transfer. Indeed, beneficaries are created automatically when receiving a Core Direct Debit and therefor by looking at the list you won't be able to idnetify which beneficary to use on SCT.
 * @member {Boolean} usableForSct
 * @default false
 */
InlineResponse2003Beneficiaries.prototype.usableForSct = false;

/**
 * @member {Array.<String>} sddCoreKnownUniqueMandateReference
 */
InlineResponse2003Beneficiaries.prototype.sddCoreKnownUniqueMandateReference = undefined;

/**
 * Creation date.
 * @member {String} createdDate
 */
InlineResponse2003Beneficiaries.prototype.createdDate = undefined;

/**
 * Update date.
 * @member {String} modifiedDate
 */
InlineResponse2003Beneficiaries.prototype.modifiedDate = undefined;

