/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2006RestrictionGroupLimits model module.
 * @module model/InlineResponse2006RestrictionGroupLimits
 * @version 0.1.1
 */
export class InlineResponse2006RestrictionGroupLimits {
  /**
   * Constructs a new <code>InlineResponse2006RestrictionGroupLimits</code>.
   * @alias module:model/InlineResponse2006RestrictionGroupLimits
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2006RestrictionGroupLimits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006RestrictionGroupLimits} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006RestrictionGroupLimits} The populated <code>InlineResponse2006RestrictionGroupLimits</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2006RestrictionGroupLimits();
      if (data.hasOwnProperty('paymentDailyLimit'))
        obj.paymentDailyLimit = ApiClient.convertToType(data['paymentDailyLimit'], 'Number');
      if (data.hasOwnProperty('mccRestrictionGroups'))
        obj.mccRestrictionGroups = ApiClient.convertToType(data['mccRestrictionGroups'], 'Number');
      if (data.hasOwnProperty('countryRestrictionGroups'))
        obj.countryRestrictionGroups = ApiClient.convertToType(data['countryRestrictionGroups'], 'Number');
      if (data.hasOwnProperty('merchantIdRestrictionGroups'))
        obj.merchantIdRestrictionGroups = ApiClient.convertToType(data['merchantIdRestrictionGroups'], 'Number');
      if (data.hasOwnProperty('required'))
        obj.required = ApiClient.convertToType(data['required'], Object);
    }
    return obj;
  }
}

/**
 * @member {Number} paymentDailyLimit
 */
InlineResponse2006RestrictionGroupLimits.prototype.paymentDailyLimit = undefined;

/**
 * @member {Number} mccRestrictionGroups
 */
InlineResponse2006RestrictionGroupLimits.prototype.mccRestrictionGroups = undefined;

/**
 * @member {Number} countryRestrictionGroups
 */
InlineResponse2006RestrictionGroupLimits.prototype.countryRestrictionGroups = undefined;

/**
 * @member {Number} merchantIdRestrictionGroups
 */
InlineResponse2006RestrictionGroupLimits.prototype.merchantIdRestrictionGroups = undefined;

/**
 * @member {Object} required
 */
InlineResponse2006RestrictionGroupLimits.prototype.required = undefined;

