/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20018Payinrefunds model module.
 * @module model/InlineResponse20018Payinrefunds
 * @version 0.1.1
 */
export class InlineResponse20018Payinrefunds {
  /**
   * Constructs a new <code>InlineResponse20018Payinrefunds</code>.
   * @alias module:model/InlineResponse20018Payinrefunds
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20018Payinrefunds</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20018Payinrefunds} obj Optional instance to populate.
   * @return {module:model/InlineResponse20018Payinrefunds} The populated <code>InlineResponse20018Payinrefunds</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20018Payinrefunds();
      if (data.hasOwnProperty('payinrefundId'))
        obj.payinrefundId = ApiClient.convertToType(data['payinrefundId'], 'Number');
      if (data.hasOwnProperty('payinrefundTag'))
        obj.payinrefundTag = ApiClient.convertToType(data['payinrefundTag'], 'String');
      if (data.hasOwnProperty('payinrefundStatus'))
        obj.payinrefundStatus = ApiClient.convertToType(data['payinrefundStatus'], 'String');
      if (data.hasOwnProperty('walletId'))
        obj.walletId = ApiClient.convertToType(data['walletId'], 'Number');
      if (data.hasOwnProperty('payinId'))
        obj.payinId = ApiClient.convertToType(data['payinId'], 'Number');
      if (data.hasOwnProperty('payinrefundDate'))
        obj.payinrefundDate = ApiClient.convertToType(data['payinrefundDate'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('modifiedDate'))
        obj.modifiedDate = ApiClient.convertToType(data['modifiedDate'], 'String');
      if (data.hasOwnProperty('totalRows'))
        obj.totalRows = ApiClient.convertToType(data['totalRows'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} payinrefundId
 */
InlineResponse20018Payinrefunds.prototype.payinrefundId = undefined;

/**
 * @member {String} payinrefundTag
 */
InlineResponse20018Payinrefunds.prototype.payinrefundTag = undefined;

/**
 * Allowed values for the <code>payinrefundStatus</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse20018Payinrefunds.PayinrefundStatusEnum = {
  /**
   * value: "PENDING"
   * @const
   */
  PENDING: "PENDING",

  /**
   * value: "CANCELED"
   * @const
   */
  CANCELED: "CANCELED",

  /**
   * value: "VALIDATED"
   * @const
   */
  VALIDATED: "VALIDATED"
};
/**
 * @member {module:model/InlineResponse20018Payinrefunds.PayinrefundStatusEnum} payinrefundStatus
 */
InlineResponse20018Payinrefunds.prototype.payinrefundStatus = undefined;

/**
 * @member {Number} walletId
 */
InlineResponse20018Payinrefunds.prototype.walletId = undefined;

/**
 * @member {Number} payinId
 */
InlineResponse20018Payinrefunds.prototype.payinId = undefined;

/**
 * @member {Number} payinrefundDate
 */
InlineResponse20018Payinrefunds.prototype.payinrefundDate = undefined;

/**
 * @member {String} amount
 */
InlineResponse20018Payinrefunds.prototype.amount = undefined;

/**
 * @member {String} currency
 */
InlineResponse20018Payinrefunds.prototype.currency = undefined;

/**
 * Date YYYY-MM-DD HH:MM:SS
 * @member {String} createdDate
 */
InlineResponse20018Payinrefunds.prototype.createdDate = undefined;

/**
 * Date YYYY-MM-DD HH:MM:SS
 * @member {String} modifiedDate
 */
InlineResponse20018Payinrefunds.prototype.modifiedDate = undefined;

/**
 * @member {Number} totalRows
 */
InlineResponse20018Payinrefunds.prototype.totalRows = undefined;

