/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {InlineResponse20020} from '../model/InlineResponse20020';
import {InlineResponseDefault} from '../model/InlineResponseDefault';

/**
* PayoutRefunds service.
* @module api/PayoutRefundsApi
* @version 0.1.1
*/
export class PayoutRefundsApi {

    /**
    * Constructs a new PayoutRefundsApi. 
    * @alias module:api/PayoutRefundsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getPayoutRefunds operation.
     * @callback moduleapi/PayoutRefundsApi~getPayoutRefundsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20020{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * search pay outs refund
     * Get pay out refund that match search criteria.
     * @param {Object} opts Optional parameters
     * @param {String} opts.accessSignature Access signature can be mandatory for specific context. Treezor will contact you if so. More info [here](https://agent.treezor.com/security-authentication).
     * @param {String} opts.accessTag Access tag is used for idem potency query. More info [here](https://agent.treezor.com/basics).
     * @param {Number} opts.accessUserId Access user&#x27;s id is used for user&#x27;s action restriction. More info [here](https://agent.treezor.com/basics).
     * @param {String} opts.accessUserIp Access user&#x27;s ip is used for user&#x27;s action restriction. More info [here](https://agent.treezor.com/basics).
     * @param {Number} opts.id PayoutRefund id
     * @param {String} opts.tag PayoutRefund tag
     * @param {String} opts.codeStatus PayoutRefund Code Status
     * @param {String} opts.informationStatus PayoutRefund Information Status
     * @param {Number} opts.payoutId Payout Id
     * @param {Number} opts.pageNumber The page number
     * @param {module:api/PayoutRefundsApi~getPayoutRefundsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPayoutRefunds(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'accessSignature': opts['accessSignature'],'accessTag': opts['accessTag'],'accessUserId': opts['accessUserId'],'accessUserIp': opts['accessUserIp'],'id': opts['id'],'tag': opts['tag'],'codeStatus': opts['codeStatus'],'informationStatus': opts['informationStatus'],'payoutId': opts['payoutId'],'pageNumber': opts['pageNumber']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20020;

      return this.apiClient.callApi(
        '/payoutRefunds', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}