/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2006RestrictionGroupLimits', function() {
      beforeEach(function() {
        instance = new Treezor.InlineResponse2006RestrictionGroupLimits();
      });

      it('should create an instance of InlineResponse2006RestrictionGroupLimits', function() {
        // TODO: update the code to test InlineResponse2006RestrictionGroupLimits
        expect(instance).to.be.a(Treezor.InlineResponse2006RestrictionGroupLimits);
      });

      it('should have the property paymentDailyLimit (base name: "paymentDailyLimit")', function() {
        // TODO: update the code to test the property paymentDailyLimit
        expect(instance).to.have.property('paymentDailyLimit');
        // expect(instance.paymentDailyLimit).to.be(expectedValueLiteral);
      });

      it('should have the property mccRestrictionGroups (base name: "mccRestrictionGroups")', function() {
        // TODO: update the code to test the property mccRestrictionGroups
        expect(instance).to.have.property('mccRestrictionGroups');
        // expect(instance.mccRestrictionGroups).to.be(expectedValueLiteral);
      });

      it('should have the property countryRestrictionGroups (base name: "countryRestrictionGroups")', function() {
        // TODO: update the code to test the property countryRestrictionGroups
        expect(instance).to.have.property('countryRestrictionGroups');
        // expect(instance.countryRestrictionGroups).to.be(expectedValueLiteral);
      });

      it('should have the property merchantIdRestrictionGroups (base name: "merchantIdRestrictionGroups")', function() {
        // TODO: update the code to test the property merchantIdRestrictionGroups
        expect(instance).to.have.property('merchantIdRestrictionGroups');
        // expect(instance.merchantIdRestrictionGroups).to.be(expectedValueLiteral);
      });

      it('should have the property required (base name: "required")', function() {
        // TODO: update the code to test the property required
        expect(instance).to.have.property('required');
        // expect(instance.required).to.be(expectedValueLiteral);
      });

    });
  });

}));
