/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20026Transfers', function() {
      beforeEach(function() {
        instance = new Treezor.InlineResponse20026Transfers();
      });

      it('should create an instance of InlineResponse20026Transfers', function() {
        // TODO: update the code to test InlineResponse20026Transfers
        expect(instance).to.be.a(Treezor.InlineResponse20026Transfers);
      });

      it('should have the property transferrefundId (base name: "transferrefundId")', function() {
        // TODO: update the code to test the property transferrefundId
        expect(instance).to.have.property('transferrefundId');
        // expect(instance.transferrefundId).to.be(expectedValueLiteral);
      });

      it('should have the property transferrefundTag (base name: "transferrefundTag")', function() {
        // TODO: update the code to test the property transferrefundTag
        expect(instance).to.have.property('transferrefundTag');
        // expect(instance.transferrefundTag).to.be(expectedValueLiteral);
      });

      it('should have the property transferrefundStatus (base name: "transferrefundStatus")', function() {
        // TODO: update the code to test the property transferrefundStatus
        expect(instance).to.have.property('transferrefundStatus');
        // expect(instance.transferrefundStatus).to.be(expectedValueLiteral);
      });

      it('should have the property codeStatus (base name: "codeStatus")', function() {
        // TODO: update the code to test the property codeStatus
        expect(instance).to.have.property('codeStatus');
        // expect(instance.codeStatus).to.be(expectedValueLiteral);
      });

      it('should have the property informationStatus (base name: "informationStatus")', function() {
        // TODO: update the code to test the property informationStatus
        expect(instance).to.have.property('informationStatus');
        // expect(instance.informationStatus).to.be(expectedValueLiteral);
      });

      it('should have the property walletId (base name: "walletId")', function() {
        // TODO: update the code to test the property walletId
        expect(instance).to.have.property('walletId');
        // expect(instance.walletId).to.be(expectedValueLiteral);
      });

      it('should have the property transferId (base name: "transferId")', function() {
        // TODO: update the code to test the property transferId
        expect(instance).to.have.property('transferId');
        // expect(instance.transferId).to.be(expectedValueLiteral);
      });

      it('should have the property transferrefundDate (base name: "transferrefundDate")', function() {
        // TODO: update the code to test the property transferrefundDate
        expect(instance).to.have.property('transferrefundDate');
        // expect(instance.transferrefundDate).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property currency (base name: "currency")', function() {
        // TODO: update the code to test the property currency
        expect(instance).to.have.property('currency');
        // expect(instance.currency).to.be(expectedValueLiteral);
      });

      it('should have the property createdDate (base name: "createdDate")', function() {
        // TODO: update the code to test the property createdDate
        expect(instance).to.have.property('createdDate');
        // expect(instance.createdDate).to.be(expectedValueLiteral);
      });

      it('should have the property modifiedDate (base name: "modifiedDate")', function() {
        // TODO: update the code to test the property modifiedDate
        expect(instance).to.have.property('modifiedDate');
        // expect(instance.modifiedDate).to.be(expectedValueLiteral);
      });

      it('should have the property totalRows (base name: "totalRows")', function() {
        // TODO: update the code to test the property totalRows
        expect(instance).to.have.property('totalRows');
        // expect(instance.totalRows).to.be(expectedValueLiteral);
      });

    });
  });

}));
