/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IssuerInitiatedDigitizationDatasBody', function() {
      beforeEach(function() {
        instance = new Treezor.IssuerInitiatedDigitizationDatasBody();
      });

      it('should create an instance of IssuerInitiatedDigitizationDatasBody', function() {
        // TODO: update the code to test IssuerInitiatedDigitizationDatasBody
        expect(instance).to.be.a(Treezor.IssuerInitiatedDigitizationDatasBody);
      });

      it('should have the property cardId (base name: "cardId")', function() {
        // TODO: update the code to test the property cardId
        expect(instance).to.have.property('cardId');
        // expect(instance.cardId).to.be(expectedValueLiteral);
      });

      it('should have the property tokenRequestor (base name: "tokenRequestor")', function() {
        // TODO: update the code to test the property tokenRequestor
        expect(instance).to.have.property('tokenRequestor');
        // expect(instance.tokenRequestor).to.be(expectedValueLiteral);
      });

      it('should have the property additionnalData (base name: "additionnalData")', function() {
        // TODO: update the code to test the property additionnalData
        expect(instance).to.have.property('additionnalData');
        // expect(instance.additionnalData).to.be(expectedValueLiteral);
      });

    });
  });

}));
