/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IssuerInitiatedDigitizationDatasAdditionnalData', function() {
      beforeEach(function() {
        instance = new Treezor.IssuerInitiatedDigitizationDatasAdditionnalData();
      });

      it('should create an instance of IssuerInitiatedDigitizationDatasAdditionnalData', function() {
        // TODO: update the code to test IssuerInitiatedDigitizationDatasAdditionnalData
        expect(instance).to.be.a(Treezor.IssuerInitiatedDigitizationDatasAdditionnalData);
      });

      it('should have the property certificates (base name: "certificates")', function() {
        // TODO: update the code to test the property certificates
        expect(instance).to.have.property('certificates');
        // expect(instance.certificates).to.be(expectedValueLiteral);
      });

      it('should have the property nonce (base name: "nonce")', function() {
        // TODO: update the code to test the property nonce
        expect(instance).to.have.property('nonce');
        // expect(instance.nonce).to.be(expectedValueLiteral);
      });

      it('should have the property nonceSignature (base name: "nonceSignature")', function() {
        // TODO: update the code to test the property nonceSignature
        expect(instance).to.have.property('nonceSignature');
        // expect(instance.nonceSignature).to.be(expectedValueLiteral);
      });

    });
  });

}));
