/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Treezor.MandateApi();
  });

  describe('(package)', function() {
    describe('MandateApi', function() {
      describe('deleteMandate', function() {
        it('should call deleteMandate successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteMandate call and complete the assertions
          /*

          instance.deleteMandate(id, origin, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMandate', function() {
        it('should call getMandate successfully', function(done) {
          // TODO: uncomment, update parameter values for getMandate call and complete the assertions
          /*

          instance.getMandate(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMandates', function() {
        it('should call getMandates successfully', function(done) {
          // TODO: uncomment, update parameter values for getMandates call and complete the assertions
          /*
          var opts = {};

          instance.getMandates(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('mandatesIdResendOtpPut', function() {
        it('should call mandatesIdResendOtpPut successfully', function(done) {
          // TODO: uncomment, update parameter values for mandatesIdResendOtpPut call and complete the assertions
          /*
          var opts = {};

          instance.mandatesIdResendOtpPut(id, accessToken, accessSignature, userId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('mandatesIdSignPut', function() {
        it('should call mandatesIdSignPut successfully', function(done) {
          // TODO: uncomment, update parameter values for mandatesIdSignPut call and complete the assertions
          /*
          var opts = {};

          instance.mandatesIdSignPut(id, accessToken, accessSignature, userId, otp, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postMandates', function() {
        it('should call postMandates successfully', function(done) {
          // TODO: uncomment, update parameter values for postMandates call and complete the assertions
          /*
          var opts = {};

          instance.postMandates(sddType, isPaper, userId, debtorName, debtorAddress, debtorCity, debtorZipCode, debtorCountry, debtorIban, sequenceType, createdIp, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
