/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Treezor.MccRestrictionGroupsApi();
  });

  describe('(package)', function() {
    describe('MccRestrictionGroupsApi', function() {
      describe('deleteMccRestrictionGroups', function() {
        it('should call deleteMccRestrictionGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteMccRestrictionGroups call and complete the assertions
          /*
          var opts = {};

          instance.deleteMccRestrictionGroups(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMccRestrictionGroups', function() {
        it('should call getMccRestrictionGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for getMccRestrictionGroups call and complete the assertions
          /*
          var opts = {};

          instance.getMccRestrictionGroups(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMccRestrictionGroupsId', function() {
        it('should call getMccRestrictionGroupsId successfully', function(done) {
          // TODO: uncomment, update parameter values for getMccRestrictionGroupsId call and complete the assertions
          /*
          var opts = {};

          instance.getMccRestrictionGroupsId(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postMccRestrictionGroup', function() {
        it('should call postMccRestrictionGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for postMccRestrictionGroup call and complete the assertions
          /*
          var opts = {};

          instance.postMccRestrictionGroup(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putMccRestrictionGroups', function() {
        it('should call putMccRestrictionGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for putMccRestrictionGroups call and complete the assertions
          /*
          var opts = {};

          instance.putMccRestrictionGroups(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
