/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Treezor.TaxResidenceApi();
  });

  describe('(package)', function() {
    describe('TaxResidenceApi', function() {
      describe('taxResidencesGet', function() {
        it('should call taxResidencesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for taxResidencesGet call and complete the assertions
          /*
          var opts = {};

          instance.taxResidencesGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('taxResidencesIdDelete', function() {
        it('should call taxResidencesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for taxResidencesIdDelete call and complete the assertions
          /*
          var opts = {};

          instance.taxResidencesIdDelete(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('taxResidencesIdGet', function() {
        it('should call taxResidencesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for taxResidencesIdGet call and complete the assertions
          /*
          var opts = {};

          instance.taxResidencesIdGet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('taxResidencesIdPut', function() {
        it('should call taxResidencesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for taxResidencesIdPut call and complete the assertions
          /*
          var opts = {};

          instance.taxResidencesIdPut(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('taxResidencesPost', function() {
        it('should call taxResidencesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for taxResidencesPost call and complete the assertions
          /*
          var opts = {};

          instance.taxResidencesPost(userId, country, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
