/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Treezor);
  }
}(this, function(expect, Treezor) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Treezor.WalletApi();
  });

  describe('(package)', function() {
    describe('WalletApi', function() {
      describe('deleteWallet', function() {
        it('should call deleteWallet successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteWallet call and complete the assertions
          /*
          var opts = {};

          instance.deleteWallet(id, origin, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getWallet', function() {
        it('should call getWallet successfully', function(done) {
          // TODO: uncomment, update parameter values for getWallet call and complete the assertions
          /*
          var opts = {};

          instance.getWallet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getWallets', function() {
        it('should call getWallets successfully', function(done) {
          // TODO: uncomment, update parameter values for getWallets call and complete the assertions
          /*
          var opts = {};

          instance.getWallets(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postWallets', function() {
        it('should call postWallets successfully', function(done) {
          // TODO: uncomment, update parameter values for postWallets call and complete the assertions
          /*
          var opts = {};

          instance.postWallets(walletTypeId, tariffId, userId, currency, eventName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putWallet', function() {
        it('should call putWallet successfully', function(done) {
          // TODO: uncomment, update parameter values for putWallet call and complete the assertions
          /*
          var opts = {};

          instance.putWallet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Treezor.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
